# Generated by Django 5.2.9 on 2026-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('procurement', 'Procurement Officer'), ('inventory', 'Inventory Manager'), ('sales', 'Sales Executive'), ('finance', 'Finance Manager')], default='sales', max_length=20),
        ),
    ]
