# Generated by Django 5.2.9 on 2026-01-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('procurement', 'Procurement Officer'), ('inventory', 'Inventory Manager'), ('sales', 'Sales Executive'), ('finance', 'Finance Manager')], default='sales', help_text='Designated role for system access control', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_users',
        ),
    ]
