# Generated by Django 5.2.9 on 2026-01-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_email_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('procurement', 'Procurement Officer'), ('inventory', 'Inventory Manager'), ('sales', 'Sales Executive'), ('finance', 'Finance Manager'), ('vendor', 'Vendor/Supplier'), ('customer', 'Customer')], default='sales', help_text='Designated role for system access control', max_length=20),
        ),
    ]
