# Generated by Django 5.2.9 on 2026-01-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='orders.salesorder'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='finance.transaction'),
        ),
    ]
