# Generated by Django 5.2.9 on 2026-01-05 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('batch_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('issued_quantity', models.IntegerField(help_text='Stock table se minus hone wale bundle/count')),
                ('issued_weight', models.DecimalField(decimal_places=2, help_text='Total Weight of Bundles in tones', max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('total_produced_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_scrap_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('process_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Jitna loha process mein burn/waste ho gaya', max_digits=10)),
                ('status', models.CharField(choices=[('issued', 'Material Issued (On Floor)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_batches', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Stock table mein plus hone wale sheets/items')),
                ('weight', models.DecimalField(decimal_places=2, help_text='In products ka total weight', max_digits=10)),
                ('is_scrap', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
